### ISSUE TITLE
Missing / Incorrect Sensors

### ISSUE THREAD

**Issue by adamlc** [jampez77/Yodel#1]
Thanks for this great integration! I've just been able to test it with a delivery thats due today.

I'm missing the sensor that I believe should say the parcels that are being delivered today.

![image](https://github.com/user-attachments/assets/fba3d066-3b67-4ae7-b0d6-bf52c22723f6)

Also the sensor for the actual parcel is displaying my email address instead of the actual parcel name.

I can see the expected name, `Gousto` in the attributes if it helps!

![image](https://github.com/user-attachments/assets/d95d599b-f721-4bd8-a011-0c79e88ff3fd)

**Comment by jampez77** [comment]
Hi, first of all. Thanks for using this integration. AFAIK You're the first to do so 😀

Second, thanks for creating an issue ☺️

The tracked parcels sensor has an 'deliveries today' attribute that provides a list of parcel numbers that are at the stage in the delivery network. 

The email thing is odd and I shall look into it as soon as I can. 😀

**Comment by adamlc** [comment]
No problem! Great to see some integrations for UK couriers!

Noted about the deliveries today attribute. I wrongly assumed it would be a sensor as I'm also using your RM integration too 👍

**Comment by jampez77** [comment]
Yeah arguably they should be the same, I keep discovering different ways to do things though haha

FYI the RM integration needs some work. I tracked a parcel and it ended up not really working. I'll be looking into it soon though 😊

**Comment by jampez77** [comment]
Thanks for using them though! It's a huge help having other users

**Comment by jampez77** [comment]
Hi, so i've finally had the time to look at this issue.

The good news is that it's an "easy" fix.

The bad news is, well there isn't any bad news but it's worth saying that the client name will never be displayed. The parcel nickname will be displayed (set via the Yodel app or HA service call) or the parcel number.

The other point worth mentioning is that i currently don't have a Yodel parcel with which to test so this work has been done blind.

Anyway it should be fixed in [2024.10.0](https://github.com/jampez77/Yodel/releases/tag/2024.10.0) but i'll keep the issue open for now just in case.

**Comment by adamlc** [comment]
@jampez77 thanks for taking a look. I have just updated myself and luckily I have a parcel coming today.

Looks like its fixed! I can confirm it displays the parcel number for the entity. I then added a nickname and then reloaded the integration and it displayed that correctly. 

Looks great, thanks!
